/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:e345989b-516a-43ab-a2cc-ff15dcc28b0a",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_D9wzlZlBv",
    "aws_user_pools_web_client_id": "21g2vaae8o97l4r8kbia7lstpp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jigqnnrgwrb6bbtjl6x7b2rbj4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5amdwc7a5zhhroseo77dgehrve",
    "aws_user_files_s3_bucket": "amplifyappbef958d8d0384010b1e19a6dca907a26235612-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
